### PR TITLE
Various cleanups and fixes

### PR DESCRIPTION
**Pull request by KellerFuchs**
This is the work I put into a “fork” of `pam_setquota` that I was considering for use by [#!](https://hashbang.sh).
While I dropped this idea and am rewriting the PAM module in Rust, I believe this patchset is worth merging:

- It fixes a major bug: `/some/path` would be considered to be a parent of `/some/paththat/is/longer`;  
  for instance, a user with homedir `/home2/foo` (contained in the root fs) would get quotas applied to `/home`.
- It uses various compile-time and linking-time hardening tricks.
- It removes a `strncmp` anti-pattern, simplifying quite a bit that code path.
- It uniformises the code style.
- It adds helpful warnings when the user defines a soft limit without the matching hard limit.

Note that, should you merge this, you will probably want to obtain a different token for the [Coverity Scan](https://scan.coverity.com) static analyzer.

### CODE REVIEW

**Comment by shartge** [comment]
Thank you for your work. I will review your changes as soon as I have some time, probably this week.

**Comment by KellerFuchs** [comment]
@shartge Ping?

**Comment by shartge** [comment]
I am sorry, but the start of the semester provided more than enough work for me. Please be patient a little bit longer, until the dust has settled and I can devote more than 15 consecutive minutes to the PR.

**Comment by KellerFuchs** [comment]
No problem, I just wanted to make sure you remembered it.

**Comment by shartge** [comment]
If you could provide a PR without the Travis/CI stuff and one with only those parts, I may be able to review and merge the changes sooner without first having to figure out how that works and then procure my own credentials for that service.

**Comment by KellerFuchs** [comment]
@shartge OK, opening two separate PRs.
I'm closing this one, because making a PR from our own development branch was a bad idea (esp. now that we decided to diverge from your code).

**Pull request closed without merging**
